### ISSUE TITLE
Dual extruder system question

### ISSUE THREAD

**Issue by Drzet** [maocypher/Octoprint-Smart-Filament-Sensor#16]
I have a single sensor attached to a E2 extruder. Another extruder doesn't have any sensors on it.
So far I had one instance of filament jamming detection, but that was a single extruder print. 
During a dual print I had no trigger events even though there is no filament movement while E1 is extruding
Question:
How is this plugin supposed to behave during dual extrusion print?
Is it possible to have 2 filament sensors ?

**Comment by maocypher** [comment]
Hi, currently this feature is under development.
If you can provide me a gcode snippet I can check if there is something different.
A volunteer checked a version for 4 extruders that worked so far.
But the detection on the one extruder should work anyway

**Comment by Drzet** [comment]
Sorry, I am not sure what "g-code snippet" means.
How does this plugin know which extruder it is monitoring?

**Comment by maocypher** [comment]
With GCode snippet I mean a few lines from your gcode.
I assume there is a tool change somewhere.
This is currently not supported, but under development.

G1 and G0 commands don't contain an identifier which extruder is used. I.e. if the tool is changed the passed distance is still messures, but no movement is detected.

I can keep this in mind to support less sensors then extruders.

**Comment by Drzet** [comment]
Thanks for the explanation. I've checked my dual extrusion gcodes, it's simple T0 and T1 commands.
From what you said, it sounds like the sensor _should_ trigger while the tool with NO sensor attached is printing, right ? I am surprised it does not.
